#!/sbin/sh

BBOX="/sbin/busybox"

######FS MOUNT PROBE SCRIPT
SYSTEM="/dev/block/mmcblk0p19"
DATA="/dev/block/mmcblk0p21"
CACHE="/dev/block/mmcblk0p18"
PRELOAD="/dev/block/mmcblk0p20"

$BBOX mount -o rw,remount /

mkdir /system && mkdir /data && mkdir /cache && mkdir /preload;

# /system
$BBOX mount -t ext4 -o ro,noatime,nodiratime $SYSTEM /system && echo " /system mounted as ext4" || echo "----> Because /system is either already mounted as ext4 or isnt ext4";
if ! [ "`grep system /proc/mounts`" ];
	then
	$BBOX mount -t f2fs -o ro,noatime,nodiratime,background_gc=off $SYSTEM /system &&	echo " /system mounted as f2fs";
fi

# /data
$BBOX mount -t ext4 -o noatime,nosuid,nodev,nodiratime,discard,barrier=0 $DATA /data && echo " /data mounted as ext4" || echo "----> Because /data is either already mounted as ext4 or isnt ext4";
if ! [ "`grep data /proc/mounts`" ];
	then
	$BBOX mount -t f2fs -o noatime,nosuid,nodev,nodiratime,background_gc=off $DATA /data && echo " /data mounted as f2fs";
fi

# /cache
$BBOX mount -t ext4 -o noatime,nosuid,nodev,nodiratime,discard,barrier=0 $CACHE /cache && echo " /cache mounted as ext4" || echo "----> Because /cache is either already mounted as ext4 or isnt ext4";
if ! [ "`grep cache /proc/mounts`" ];
	then
	$BBOX mount -t f2fs -o noatime,nosuid,nodev,nodiratime,background_gc=off $CACHE /cache && echo " /cache mounted as f2fs";
fi

# /preload
$BBOX mount -t ext4 -o noatime,nosuid,nodev,nodiratime,discard,barrier=0 $PRELOAD /preload && echo " /preload mounted as ext4" || echo "----> Because /preload is either already mounted as ext4 or isnt ext4";
if ! [ "`grep preload /proc/mounts`" ];
	then
	$BBOX mount -t f2fs -o noatime,nosuid,nodev,nodiratime,background_gc=off $PRELOAD /preload && echo " /preload mounted as f2fs" || echo "----> Because /preload is a swap partition";
fi

$BBOX mount -o ro,remount /
